/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author zgree_000
 */
public class StatusUpdater extends ZFrame {

    /**
     * Creates new form BootWaitScreen
     * @param indeterminate - the style of leading bar to be used
     */
    public StatusUpdater(boolean indeterminate) {
        initComponents();
        pack(null);
        statusDisplay.setEditable(false);
        loadingProgress.setIndeterminate(indeterminate);
    }

    public void println(String in){
        statusDisplay.append(in + "\n");
        statusDisplay.setCaretPosition(statusDisplay.getDocument().getLength());
    }
    
    public void print(String in){
        statusDisplay.append(in);
        statusDisplay.setCaretPosition(statusDisplay.getDocument().getLength());
    }
    
    public void complete(){
        dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingProgress = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        statusDisplayPanel = new javax.swing.JScrollPane();
        statusDisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loading...");

        loadingProgress.setFocusable(false);

        jLabel1.setText("LoLTracker is...");

        statusDisplay.setColumns(20);
        statusDisplay.setRows(5);
        statusDisplayPanel.setViewportView(statusDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                    .addComponent(loadingProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadingProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar loadingProgress;
    private javax.swing.JTextArea statusDisplay;
    private javax.swing.JScrollPane statusDisplayPanel;
    // End of variables declaration//GEN-END:variables
}
